#!/bin/bash

# Configuration Setup Scrip!

# ------------------------------------------------------------------------------------------------------------
# Step 1: Git 

if command -v git &> /dev/null; then 
   # this will check whether git is installed and available in the system's path

	git clone https://gitlab.com/cit2420/2420-as2-starting-files ~/config_files
else 
	echo "Your system does not have git installed, Installing git"

	# this will check if pacman is installed 
	if command -v pacman &> /dev/null; then
	
		# if it is, it installs git using pacman 
		sudo pacman -S git
	else
		echo "Error: Please install Git mmanually"
		exit 1
	fi

	git clone https://gitlab.com/cit2420/2420-as2-starting-files ~/config_files
fi 


# ----------------------------------------------------------------------------------------------------------
# Step 2: Listing all the files and directories inside the cloned repository


   config_repo="$HOME/config_files"
   # im setting confif_repo to the path of the cloned config files directory
   # inside the user's home directory 

   content_files=$(find "$config_repo" -maxdepth 1 -mindepth 1 -type d)
   # Im using find to search for the direcotries inside 'config_repo'
   	# -maxdepth 1 = will only search one level deep inside the direcetoy
	# -mindepth 1 = will not include the root directory - skipping 'config_repo' 

# ------------------------------------------------------------------------------------------------------------

# step 3: Connecting symbolic links to our files 


  for content in $content_files; do

      #Here we are getting the abosolute path of the directory
      dir=$(basename "$content")

      case "$dir" in
          "bin")
	  	target="$HOME/bin" # will set the target for the bin directory
		;;

	  "config")
	        target="$HOME/.config" # will set the target for the bin directory
		;;

   	  "home")
	       target="$HOME/.bashrc" # will set the target for the bin directory
	       ln -s "$content/bashrc" "$target"
	       continue
	       ;;
      esac
     
      # Now will create for bin, config
      if [ ! -e "$target" ]; then 
	      # checks if the symlink already exist

         ln -s "$content" "$target"
	 # will create the symlink 
	 echo "created symlink: $target -> $content"
      else 
         echo "Symlink already exists: $target"
      fi

done

echo "Configuration was a success"
